// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharpSpreadsheetML")>]
[<assembly: AssemblyProductAttribute("FSharpSpreadsheetML")>]
[<assembly: AssemblyDescriptionAttribute("FSharp wrapper for Open XML SDK, allowing Excel File reading and manipulation")>]
[<assembly: AssemblyVersionAttribute("0.0.3")>]
[<assembly: AssemblyFileVersionAttribute("0.0.3")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharpSpreadsheetML"
    let [<Literal>] AssemblyProduct = "FSharpSpreadsheetML"
    let [<Literal>] AssemblyDescription = "FSharp wrapper for Open XML SDK, allowing Excel File reading and manipulation"
    let [<Literal>] AssemblyVersion = "0.0.3"
    let [<Literal>] AssemblyFileVersion = "0.0.3"
    let [<Literal>] AssemblyConfiguration = "Release"
